import { Sidebar } from '@/components/global/sidebar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { ThemeProviders } from '@/theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning lang="en" className="antialiased">
      <body className={inter.className}>
        <ThemeProviders>
          <div className="min-h-screen lg:grid lg:grid-cols-app dark:bg-zinc-900">
            <Sidebar />
            <main className="max-w-[100vw] px-4 pb-12 pt-24 lg:col-start-2">
              {children}
            </main>
          </div>
        </ThemeProviders>
      </body>
    </html>
  )
}
